---
    # Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. SPDX-License-Identifier: MIT-0
    # This pipeline is for running license checks with ./scripts/check-licenses.sh
    name: License-Checks
    
    # Controls when the workflow will run
    on:
      push:
        # Triggers the workflow for feature branches and main (final confirmation)
        branches:
          - "bugfix/*"
          - "feature/*"
          - "main"
      pull_request:
        branches:
          - main
          - release/*
    
    jobs:
      CheckLicenses:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - uses: actions/setup-node@v3
            with:
              node-version: 18
          - uses: actions/setup-python@v2
            with:
              python-version: 3.11
          - name: Check-Licenses
            run: ./scripts/check-licenses.sh
    